I = imread('b.tif');
udata = [0 1];  vdata = [0 1];

tform = maketform('projective',[ 0 0;  1  0;  1  1; 0 1],...
                               [ -10 -10; 1 0; 1 1; 0 1]);

[B,xdata,ydata] = imtransform(I,tform,'bicubic', ...
                              'udata',udata,...
                              'vdata',vdata,...
                              'size',size(I),...
                              'fill',128);
subplot(1,2,1); imshow(I,'XData',udata,'YData',vdata)
subplot(1,2,2); imshow(B,'XData',xdata,'YData',ydata)